### ISSUE TITLE
User Stories #1: Form and List

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#1]
# User Story #1: Form and List

## Value Proposition:

- **As a** user
- **I want to** log my mood AND see a list of my entries
- **so that I** can track my emotions over time

## Description

![Image](https://github.com/MathiSans/mood-diary/assets/148473781/e557cec8-f87d-4d99-8537-67212738bac4)

## Acceptance Criteria:

- [ ] a slider to assess my current mood
- [ ] multiple choice selection of further describing emotions
- [ ] input field for the user to add a more detailed description
- [ ] user can submit the entry
- [ ] submit button: submitted entries are listed as entry cards below the form entry cards include date, time and entry details app title 
- [ ] displayed at the top of the screen user gets reminded to provide input if some of it is missing
- [ ] app title displayed at the top of the screen

## Tasks:

- [ ] create new feature branch `feature/form-and-list`
- [ ] create `<h1>` for app title
- [ ] create `form`
- [ ] **slider:**
- 0-40 unpleasant
- 41-49 neutral
- 5-100 pleasant
- [ ] click-hold-drag
- [ ] **checkboxes:**
- [ ] hardcoded tags
- [ ] reset checkbox styling
- [ ] add styling to include:
- [ ] tag title
- [ ] active/inactive state
- [ ] text input field
- [ ] submit button
- [ ] separator
- [ ] entry list

**Comment by janphilipp-winkler** [comment]
![Image](https://github.com/MathiSans/mood-diary/assets/148473781/5b34adb2-9095-43f9-b3f3-a417c7662444)
