### ISSUE TITLE
User Story: New Entry Tile in Overview Column

### ISSUE THREAD

**Issue by SevketErsan** [MathiSans/capstone_mood-tracker#103]

**Comment by SevketErsan** [comment]
## Value proposition
As a user
I want a new entry tile in the overview column
In order to quickly add new entries to track my mood.

## Description

![Image](https://github.com/MathiSans/capstone_mood-tracker/assets/51250563/4a5716ce-da81-402c-ac46-ab5fc1fe617c)

## Acceptance criteria
 - [ ] A new entry tile displayed prominently in the overview column.
 - [ ] The tile should be visually distinct and easily accessible.
 - [ ] The tile should contain fields for entering moods.
 - [ ] The tile should contain icon on the left top of it.

## Tasks
 - [ ] Create a new component for the New Entry tile.
 - [ ] Design the layout of the tile component with an icon.
 - [ ] Implement functionality to input mood.
 - [ ] Integrate the tile into the overview column component.
