### ISSUE TITLE
User Story: Last Entry Tile in Overview Column

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#112]
## Value proposition
**As a** user
**I want to** see my last entry at a first glance
**In order to** asses how my mood is in comparrison to it

## Description
![Image](https://github.com/MathiSans/capstone_mood-tracker/assets/148532969/2a3d21d4-98b4-4750-867c-b31a60317bde)

## Acceptance criteria
- [ ] the user sees a tile with their last entry in the overview dashboard

## Tasks
- [ ] import useData, useSession and EntryTile in Overview
- [ ] add data: session as const
- [ ] add allEntries as const and fetch all entries
- [ ] add userEntries as const and fetch alls user specific entries
- [ ] add lastEntry as const and check if data and session is provided for user or anonymous entries
- [ ] pass all neccessary data to EntryTile in return
- [ ] add isOnOverviewColumn state to EntryTile

**Comment by mariiaovs** [comment]
Good idea! 👍
