### ISSUE TITLE
User Story: Activities Column and components inside in Dashboard

### ISSUE THREAD

**Issue by SevketErsan** [MathiSans/capstone_mood-tracker#125]

**Comment by SevketErsan** [comment]
## Value proposition

As a user, I want to have a column for the activitiers and tools within the overview column of the dashboard, 
so that i can to quickly navigate through different activities in dashboard content.

## Description



![Image](https://github.com/MathiSans/capstone_mood-tracker/assets/51250563/66be5a44-7a50-4280-984a-17161c79a7e6)



## Acceptance criteria
 - [ ] The List should be able to scroll horizontally through different tools and activities.
 - [ ] At the top of the list should be able to switch All Activities/Tools

## Tasks
 - [ ]  Create a branch `v2/ActivityColumn` 
 - [ ]  Add activitiesList
 - [ ] Connect the activitiesList with activity-form
 - [ ] Add filter function for Activities and tools
 - [ ] Ensure that the List is integrated seamlessly within the `activity column of the dashboard` interface.

**Comment by PaulJohannFlade** [comment]
Great Work. Nothing to add. Looks good to me! 👍
