### ISSUE TITLE
Dev Story: Tiles Styling

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#136]
## Value proposition
**As a** user
**I want to** look at a minimal app design
**In order to** get a quick grasp of the provided information

## Description
![Image](https://github.com/MathiSans/capstone_mood-tracker/assets/148532969/80ee99ef-ef5b-40b7-89e6-a22b32b8ddf1)

## Acceptance criteria
- [ ] a dynamic and clean design
- [ ] the sphere doesn't distract from the tiles

## Tasks
- [ ] select new colors to replace the previous ones
- [ ] write styled components or add styling to existing ones
- [ ] work with the grid layout
