### ISSUE TITLE
Dev Story: 💅🏾 Polish NewEntryFlow in v2 app

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#140]
## Value proposition
**As a** user
**I want to** look at a minimal app design
**In order to** get a quick grasp of the provided information

## Description
- design used in [Dev Story - Tiles Styling](https://github.com/users/MathiSans/projects/1/views/1?pane=issue&itemId=61673311) will be added to the Flow component

## Acceptance criteria
- [ ] a dynamic and clean design
- [ ] the sphere doesn't distract from other elements

## Tasks
- [ ] use new color palette 
- [ ] add new styling to Flow component
- [ ] work with the grid layout
