### ISSUE TITLE
User Story: Sound integration

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#26]
## Value proposition
**As a** user
**I want to** hear athmospheric and calming sound,
**so I can**  have an emersive experience while reflecting my mood

## Description
<img width="912" alt="US_Description_6" src="https://github.com/MathiSans/capstone_mood-tracker/assets/148532969/87a391ff-50d1-4f95-b301-83704610dbfb">

## Acceptance criteria
- [ ] the audio is played when accessing `focus page`
- [ ] the user can `toggle sound` on and off
- [ ] the toggle `button is prominent` on the page
- [ ] the `audio fades out` when the user proceeds in the multi-step form

## Tasks
**Preparations:**
- [ ] install `file-loader` to process mp3 files
- [ ] configure the `next.config.js` to include the loader
- [ ] add syntax so the loader can `look for mp3 files` in the project directory
- [ ] `create folders` for images and sound files in the public folder

**flow.js:**
- [ ] import audio file
- [ ] declare an `audioPlaying` useState
- [ ] add syntax after `FlowContainer` component to mount `PlaySound` for when the page index is `> 0`
- [ ] add states `audioPlaying, page` to PlaySound and image `src` for audio file
- [ ] continue with syntax to mount `PlayButton` when the page index equals `1`
- [ ] add function `hanndleIsPlaying` and state `audioPlaying`to PlayButton

**PlaySound.js:**
- [ ] create `PlaySound.js` inside an euqally named folder and add it to components folder
- [ ] import `useRef, useEffect, useState`
- [ ] write function `PlaySound` and pass props `src, play, pageIndex`
- [ ] declare `useRef` variable and set initial state to `null`
- [ ] declare `useState` variable for `currentVolume` with inital state of `0.5`
- [ ] write logic for `useEffect`:
- [ ] check if `audioPlaying`is true and `useRef` variable is not `null`->
- [ ] tif both apply `currentVolume` sets volume for `<audio>` ->
- [ ] and calls `play()` function to start playing the audio file
- [ ] add audioPlaying and currentVolume to dependancy array
- return:
- [ ] <audio> with `ref, `src` and `loop`
- [ ] <DecreaseVolume> and pass `pageIndex, currentVolume, setCurrentVolume`
- [ ] export function 

**DecreaseVolume.js:**
- [ ] import `useEffect`
- [ ] write function `DecreaseVolume` and pass props `pageIndex, currentVolume, setCurrentVolume`
- [ ] write logic for`useEffect`:
- [ ] `if pageIndex > 1` start `setInterval`
- [ ] `if currentVolume > 0` decrease Volume by `-1` every `50ms`
- [ ] return: `clearInterval`
- [ ] add `pageIndex, currentVolume, setCurrentVolume` to dependency array

**PlayButton.js:**
- [ ] import `styled, Image, playing`
- [ ] write function `PlayButton`, pass props `handleIsPlaying, audioPlaying`
- return:
- [ ] `<StyledPlayButton>`
- [ ] pass `handleIsPlaying` with `onClick` ->
- [ ] pass `audioPlaying`
- [ ] write ternary operator: if audioPlaying is set to `true` mount/display <Image> ->
- [ ] otherwise a `<p>` with "turn sound on"
- [ ] `style` the button and p tag

**Comment by MerleMak** [comment]
Amazing! I am super happy you found this out all by yourself! (Sorry for not helping more, I was distracted with reviews) But very very nice job! Supert excited to see this implemented 🤩
