### ISSUE TITLE
User Story: Play Audio for Selected Emotion

### ISSUE THREAD

**Issue by MathiSans** [MathiSans/capstone_mood-tracker#57]
## Value proposition
**As a** user
**I want to** listen to atmospheric audio
**so I can** have an immersive experience while logging my mood

## Acceptance criteria
- [ ] the user hears different audio tracks depending on which experience they select
- [ ] the tracks change when the user decides to select another experience
- [ ] instead of muting the audio the user can now press the play/pause button

## Tasks
- [ ] add an audio track for every experience the user can select
- [ ] extend the logic of `PlaySound` to target a different `audio.src` depending on the selected experience
- [ ] rewrite the logic of the MuteButton and rename it to `PlayButton`
- [ ] rename the MuteButton component in AudioSettings too
